Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -20,9 +20,9 @@ jobs:
             set -e
             set -x
 
-            A="A"
-            B="BB"
-            C="CCC"
+            A="D"
+            B="EE"
+            C="FFF"
 
             echo "##vso[task.setvariable variable=A]${A:?}"
             echo "##vso[task.setvariable variable=B]${B:?}"
@@ -37,14 +37,14 @@ jobs:
             set -e
             set -x
 
-            EXPECTED_A="A"
-            EXPECTED_B="BB"
-            EXPECTED_C="CCC"
+            EXPECTED_A="D"
+            EXPECTED_B="EE"
+            EXPECTED_C="FFF"
 
             ERROR_COUNT=0
             [ ${A:?} != "${EXPECTED_A:?}" ] && echo "ADO changed my variable A from [${EXPECTED_A:?}] to [${A:?}]" && ERROR_COUNT=$((ERROR_COUNT+1)) || echo "Variable A is OK"
-            [ ${B:?} != "${EXPECTED_B:?}" ] && echo "ADO changed my variable BB from [${EXPECTED_B:?}] to [${B:?}]" && ERROR_COUNT=$((ERROR_COUNT+1)) || echo "Variable B is OK"
-            [ ${C:?} != "${EXPECTED_C:?}" ] && echo "ADO changed my variable CCC from [${EXPECTED_C:?}] to [${C:?}]" && ERROR_COUNT=$((ERROR_COUNT+1)) || echo "Variable C is OK"
+            [ ${B:?} != "${EXPECTED_B:?}" ] && echo "ADO changed my variable B from [${EXPECTED_B:?}] to [${B:?}]" && ERROR_COUNT=$((ERROR_COUNT+1)) || echo "Variable B is OK"
+            [ ${C:?} != "${EXPECTED_C:?}" ] && echo "ADO changed my variable C from [${EXPECTED_C:?}] to [${C:?}]" && ERROR_COUNT=$((ERROR_COUNT+1)) || echo "Variable C is OK"
 
             test ${ERROR_COUNT} -eq 0 || exit 1
 
